# Generated by Django 6.1.1 on 2026-09-25 18:33

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('IGNORED', 'Ignored')], db_index=True, default='PROCESSED', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Authoritative charged amount matching the booking snapshot', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('provider_ref', models.CharField(db_index=True, help_text='Merchant-generated unique reference sent to external payment gateway', max_length=100, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Client-supplied idempotency key scoped per user', max_length=255)),
                ('flagged_for_refund', models.BooleanField(default=False, help_text='Set to True if customer was charged but booking could not be confirmed')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_user_idempotency_key'), models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('booking',), name='one_inflight_payment_per_booking'), models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='check_payment_amount_positive')],
            },
        ),
    ]
